name: Daily Penguin Prediction

on:
  schedule:
    - cron: '30 6 * * *'  # Runs every day at 7:30 AM CET (UTC+1)
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch_and_predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run prediction script
        run: python prediction.py

      - name: Commit and push prediction
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add prediction.md
          git commit -m "📈 Update daily penguin prediction"
          git push
